// Mocks generated by Mockito 5.4.0 from annotations
// in ny_times_stories_app_flutter/test/ny_times_stories/data/repositories/stories_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:dio/dio.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:stories_app_flutter/src/core/common_feature/data/entities/api_response_model.dart'
    as _i4;
import 'package:stories_app_flutter/src/core/network/rest_client.dart'
    as _i2;
import 'package:stories_app_flutter/src/features/ny_times_stories/data/data_sources/stories_api.dart'
    as _i5;
import 'package:stories_app_flutter/src/features/ny_times_stories/data/entities/story_model.dart'
    as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeRestClient_0 extends _i1.SmartFake implements _i2.RestClient {
  _FakeRestClient_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCancelToken_1 extends _i1.SmartFake implements _i3.CancelToken {
  _FakeCancelToken_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeApiResponse_2<T> extends _i1.SmartFake
    implements _i4.ApiResponse<T> {
  _FakeApiResponse_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [StoriesApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockStoriesApi extends _i1.Mock implements _i5.StoriesApi {
  MockStoriesApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.RestClient get restClient => (super.noSuchMethod(
        Invocation.getter(#restClient),
        returnValue: _FakeRestClient_0(
          this,
          Invocation.getter(#restClient),
        ),
      ) as _i2.RestClient);
  @override
  _i3.CancelToken get cancelToken => (super.noSuchMethod(
        Invocation.getter(#cancelToken),
        returnValue: _FakeCancelToken_1(
          this,
          Invocation.getter(#cancelToken),
        ),
      ) as _i3.CancelToken);
  @override
  set cancelToken(_i3.CancelToken? _cancelToken) => super.noSuchMethod(
        Invocation.setter(
          #cancelToken,
          _cancelToken,
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i6.Future<_i4.ApiResponse<List<_i7.StoryModel>>> getStories(
          String? section) =>
      (super.noSuchMethod(
        Invocation.method(
          #getStories,
          [section],
        ),
        returnValue: _i6.Future<_i4.ApiResponse<List<_i7.StoryModel>>>.value(
            _FakeApiResponse_2<List<_i7.StoryModel>>(
          this,
          Invocation.method(
            #getStories,
            [section],
          ),
        )),
      ) as _i6.Future<_i4.ApiResponse<List<_i7.StoryModel>>>);
}
